baseurl: /devops-assessment
markdown: redcarpet
name: 18F DevOps Assessment Guide
exclude:
- go
- copy-template
- Gemfile
- Gemfile.lock
- README.md
- LICENSE.md

permalink: pretty

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Introduction
  url: index.html
  internal: true
- text: Infrastructure
  url: infrastructure/
  internal: true
- text: Environments
  url: environments/
  internal: true
- text: Organizations
  url: organizations/
  internal: true

repos:
- name: 18F DevOps Assessment Guide
  description: Main repository
  url: https://github.com/18F/devops-assessment

# Style Variables
brand_color: "#1188ff"

google_analytics_ua: UA-48605964-19
